### ISSUE TITLE
Camera error: could not initialize MediaFoundation: failed to fulfill requested format

### ISSUE THREAD

**Issue by HYP3R00T** [CapSoftware/Cap#757]
### Description

I am getting `Camera error: could not initialize MediaFoundation: failed to fulfill requested format`. 

<img width="520" height="133" alt="Image" src="https://github.com/user-attachments/assets/987d8ca7-ea1b-4ff6-b4c6-c0305befb7ca" />

### Reproduction

- I installed Cap after downloading the exe file (Cap_0.3.58_x64-setup.exe) from the official website.
- I installed it to the default path it suggested
- After the fresh installation, I opened the app
- I tried selecting "DroidCam Video" as the video input.
- Then the mentioned error popped up.

#### Notes: 
- The "DroidCam Video" as input works with all other tools such OBS Studio, Loom, Google Meet, WhatsApp, etc.
- I tried using OBS Virtual Camera but it won't detect that and won't even show it in the list of camera source.
- I tried using the Nvidia Broadcast with Video enabled and it won't detect that.
- However, it can detect my inbuilt camera which works fine (though the camera sucks and don't want to use it).
- I tried reinstalling it with Admin privileges and still it failed to use "DroidCam Video" and displayed the same error.

<img width="226" height="75" alt="Image" src="https://github.com/user-attachments/assets/2098ccdb-61ce-4a7f-b40c-3de23e10b429" />

### Additional Context

- Cap version: 0.3.58
- Operating system, version: Windows 11 Home SL 24H2

```shell
ls

    Directory: C:\Users\<user-name>\AppData\Roaming\so.cap.desktop

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           7/13/2025  8:25 AM                recordings
-a---           7/13/2025  8:26 AM            691 store
```

No logs found.

**Comment by Brendonovich** [comment]
Cap isn't able to detect some virtual cameras yet, and some other cameras just seem to have issues. #752 is the start of improving our camera support on windows which I'll be continuing next week.

**Comment by sarvarbek2603** [comment]
Me too

<img width="1208" height="697" alt="Image" src="https://github.com/user-attachments/assets/203a0071-8fca-454a-9dcf-857b68e7bb00" />

**Comment by HYP3R00T** [comment]
I can see that @Brendonovich is working a new PR #788 . When can we expect it to be merged and a new updated package to be released? I really want to use Cap and been waiting for this fix.

**Comment by Brendonovich** [comment]
It'll be out very soon, [here](https://cdn.crabnebula.app/asset/01K1CSE9MF0SFNY8BP8NMYCV9A) is a beta build you can try out which should work - DroidCam and Iriun both work from my testing

**Comment by HYP3R00T** [comment]
Thanks for quick response. I can verify that all my Cameras are working seamlessly. Thanks a lot.

**Comment by sarvarbek2603** [comment]
Hi @Brendonovich 
When I turn on the camera hide feature, the last frame from the camera remains on the screen

<img width="1275" height="800" alt="Image" src="https://github.com/user-attachments/assets/14e9e06b-6c39-4f69-9eeb-afde1d19808d" />

**Comment by Brendonovich** [comment]
Both of these should be fixed in the latest release

**Comment by HYP3R00T** [comment]
@Brendonovich I can confirm that the issue with lingering overview of webcam even after turning on the "Hide Camera" is not fixed. I have created a new issue #855 for this. 

Let's take the discussion over there @sarvarbek2603
